services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'my_db'
      POSTGRES_PASSWORD: 'my.dirty.secrets'

    ports:
      - 5433:5432
  cache:
    image: redis:6.2.12
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction
